linters:
  enable-all: true
  disable:
    - exportloopref
    - depguard
    - tparallel
    - paralleltest
    - mnd
linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule
  gosec:
    excludes:
      - G404 # Insecure random number source (rand)
  funlen:
    lines: 200
    statements: 150
  importas:
    no-extra-aliases: true
    alias:
      - pkg: github.com/elemir/gloomo/id
        alias: gid
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
  varnamelen:
    ignore-names:
      - xs
      - ok
    ignore-decls:
      - i int
      - id gid.ID
      - id id.ID
      - id ID
      - x float64
      - y float64
  wsl:
    allow-cuddle-declarations: true
