linters:
  enable-all: true
  disable:
    - exportloopref
    - depguard
    - tparallel
    - paralleltest
    - mnd
    - exhaustruct
    - varnamelen
    - prealloc
linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule
  gosec:
    excludes:
      - G404 # Insecure random number source (rand)
  funlen:
    lines: 200
    statements: 150
  importas:
    no-extra-aliases: true
    alias:
      - pkg: github.com/elemir/gloomo/id
        alias: gid
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
  nlreturn:
    block-size: 2
  wsl:
    allow-cuddle-declarations: true
issues:
  exclude-rules:
  - path: _test\.go
    linters:
      - err113
