version: '3'

tasks:
  example:
    cmds:
      - go run ./example
  test:
    cmds:
      - go test ./...
  cover:
    cmds:
      - go test ./... -coverprofile=.cover.out
      - go tool cover -html=.cover.out
  lint:
    cmds:
      - golangci-lint run --fast "./..."
  lint-fix:
    cmds:
      - golangci-lint run --fix "./..."
